version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5000:80"
    networks:
      - webnet

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
      - FIRST_SUPERUSER=admin@example.com
      - FIRST_SUPERUSER_PASSWORD=adminpassword
    networks:
      - webnet  

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - webnet

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - webnet

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - "81:81"     # Admin Web Port
      - "444:443"   # HTTPS Port (changed to avoid conflict)
      - "8090:81"   # Nginx Proxy Manager GUI
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    environment:
      - DISABLE_IPV6=true
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/delightdev.ng:/etc/letsencrypt/live/delightdev.ng:ro
      - /etc/letsencrypt/archive/delightdev.ng:/etc/letsencrypt/archive/delightdev.ng:ro
    depends_on:
      - frontend
      - backend
      - nginx-proxy-manager
    networks:
      - webnet
    ports:
      - "80:80"    # Expose nginx on port 80
      - "445:443"  # Expose nginx on port 443 (changed to avoid conflict)

networks:
  webnet:

volumes:
  postgres_data:
