version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    networks:
      - webnet

  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: postgres://user:password@db:5432/mydatabase
    networks:
      - webnet

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - webnet

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - webnet

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - "80:80"  # Public HTTP Port
      - "81:81"  # Admin Web Port
      - "443:443"  # Public HTTPS Port
      - "8090:81"  # Nginx Proxy Manager GUI on port 8090
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    environment:
      - DISABLE_IPV6=true
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - webnet
    ports:
      - "80:80"

networks:
  webnet:

volumes:
  postgres_data:
